global:
  externalUrl: http://minikube.data.gov.au:30100
  rollingUpdate:
    maxUnavailable: 1
  exposeNodePorts: true
  image:
    pullSecrets: "regcred"
    pullPolicy: Always
  useCloudSql: false
  useCombinedDb: true
  enablePriorityClass: false
  openfaas:
    enabled: false

tags:
  all: false
  combined-db: true
  authorization-db: true
  registry-db: true
  opa: true
  authorization-api: true

magda-core:
  opa:
    customPolicyConfigMaps:
    - test-opa-policies