{{- if not .Values.global.useCombinedDb }}
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: authorization-db
spec:
  serviceName: authorization-db
  replicas: 1
{{- if semverCompare "^1.7.0" (printf "%s" .Capabilities.KubeVersion) }}
  updateStrategy:
    type: RollingUpdate
{{- end }}
  template:
    metadata:
      labels:
        service: authorization-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: authorization-db
        resources:
{{ toYaml .Values.resources | indent 10 }}
        image: {{ template "dockerimage" . }}
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: /var/pv/data
        - name: DEFAULT_ADMIN_USER_ID
          value: "{{ .Values.global.defaultAdminUserId }}"
        volumeMounts:
        - mountPath: /var/pv
          name: registrydata
  volumeClaimTemplates:
  - metadata:
      name: registrydata
    spec:
      accessModes: [ "ReadWriteOnce" ]
    {{- if .Values.data.storageClass }}
      storageClassName: "{{ .Values.data.storageClass }}"
    {{- end }}
      resources:
        requests:
          storage: "{{ .Values.data.storage }}"
{{- end }}
