#API

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: api
    spec:
      containers:
      - name: api
        env:
        - name: SCALA_ENV
          value: prod
        - name: MAGDA_SEARCH_ROLE
          value: api
        image: "data61/magda-metadata:v${version}"
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/instance-type: "n1-standard-1"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: api
  type: "LoadBalancer"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---

#INDEXER

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: indexer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: indexer
    spec:
      containers:
      - name: indexer
        env:
        - name: SCALA_ENV
          value: prod
        - name: MAGDA_SEARCH_ROLE
          value: indexer
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secret-key
              key: s3-secret-key
        image: "data61/magda-metadata:v${version}"
        volumeMounts:
        - mountPath: /usr/regions
          name: regions
      volumes:
      - name: regions
        emptyDir: {}
      nodeSelector:
        beta.kubernetes.io/instance-type: "n1-standard-1"