apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authorization-api
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        service: authorization-api
    spec:
      containers:
      - name: authorization-api
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        command: [
            "node",
            "/usr/src/app/component/dist/index.js",
            "--listenPort", "80",
            "--dbHost", "authorization-db",
            "--dbPort", "5432"
        ]
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: NODE_ENV
          value: production
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
{{- end }}
{{- if not .Values.global.noDbAuth }}
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-passwords
              key: auth-db
{{- end }}
