apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleuther-visualisation
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        service: sleuther-visualisation
    spec:
      containers:
      - name: sleuther-visualisation
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: NODE_PORT
          value: "80"
        - name: REGISTRY_URL
          value: "http://registry-api/v0"
        - name: USER_ID
          value: {{ .Values.global.defaultAdminUserId }}
        - name: INTERNAL_URL
          value: "http://sleuther-visualisation"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
