apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: {{ .Values.replicas | default 1 }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        service: search-api
    spec:
      containers:
      - name: search-api
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        command: [
            "/app/bin/magda-search-api",
            "-Dhttp.port=80",
            "-Dakka.loglevel={{ .Values.global.logLevel }}",
            "-DelasticSearch.serverUrl=elasticsearch://elasticsearch:9300"
        ]
        {{- if not .Values.global.noDbAuth }}
        env:
        - name: ELASTIC_SEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-passwords
              key: elasticsearch
        {{- end }}
        ports:
        - containerPort: 80
        resources:
{{ toYaml .Values.resources | indent 10 }}
