apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        service: search-api
    spec:
      containers:
      - name: search-api
        env:
        - name: SCALA_ENV
          value: dev-na # TODO
        image: {{ template "dockerimage" . }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
{{ toYaml .Values.resources | indent 10 }}
