dist: trusty
sudo: false
language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
services:
  - postgresql
env:
  global:
    - SBT_OPTS="-Xms1000M -Xmx1000M -XX:+CMSClassUnloadingEnabled -XX:MaxGCPauseMillis=100 -XX:+UseG1GC"
    - CI=true
addons:
    postgresql: "9.6"
