dist: trusty
sudo: false
matrix:
  include: 
    - language: scala
      scala: 2.11.8
      jdk: oraclejdk8
      services:
        - postgresql
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt
          - target
      before_cache:
        # Cleanup the cached directories to avoid unnecessary cache updates
        - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
        - find $HOME/.sbt        -name "*.lock"               -print -delete
      env:
        global:
          # 3gb heap, unload classes we don't need, aim for < 50ms gc pauses (largely ignored), use the next-gen collector, try to free 5% of heap every gc, use < 25% of time for GC
          - SBT_OPTS="-Xms3000M -Xmx3000M -XX:+CMSClassUnloadingEnabled -XX:MaxGCPauseMillis=1000 -XX:+UseG1GC -XX:GCTimeRatio=3"
          - CI=true
      addons:
        postgresql: "9.6"
      script: travis_retry sbt test
    - language: node_js
      node_js: node
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt
          - node_modules
          - magda-auth-api/node_modules
          - magda-broken-link-sleuther/node_modules
          - magda-discussions-api/node_modules
          - magda-gateway/node_modules
          - magda-preview-map/node_modules
          - magda-project-open-data-connector/node_modules
          - magda-sleuther-broken-link/node_modules
          - magda-sleuther-framework/node_modules
          - magda-sleuther-ld-rating/node_modules
          - magda-typescript-common/node_modules
          - magda-web-client/node_modules
          - magda-web-server/node_modules
      before_cache:
        # Cleanup the cached directories to avoid unnecessary cache updates
        - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
        - find $HOME/.sbt        -name "*.lock"               -print -delete
      script: npm install -g lerna && lerna bootstrap && npm run node-ci
      env:
        global:
          - CI=true