apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleuther-linked-data-rating
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        service: sleuther-linked-data-rating
    spec:
      containers:
      - name: sleuther-linked-data-rating
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        env:
        - name: NODE_PORT
          value: "80"
        - name: REGISTRY_URL
          value: "http://registry-api/v0"