apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: preview-map
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        service: preview-map
    spec:
      containers:
      - name: preview-map
        resources:
          requests:
            cpu: 250m
            memory: 200Mi
        env:
        - name: NODE_ENV
          value: prod
        image: "data61/magda-preview-map:${version}"
---
apiVersion: v1
kind: Service
metadata:
  name: preview-map
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3019
  selector:
    service: preview-map
  type: "NodePort"
