apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - name: web
        command: [
            'node', '/usr/src/app/component/dist/index.js',
            '--config', "/etc/config.json"
        ]
        resources:
          requests:
            cpu: 300m
            memory: 200Mi
        env:
        - name: NODE_ENV
          value: prod
        image: "data61/magda-web-server:${version}"
        volumeMounts:
        - mountPath: "/etc"
          name: config
      volumes:
      - name: config
        configMap:
          name: config
          items:
          - key: web.json
            path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - name: http
    port: 80
    targetPort: 6107
  selector:
    service: web
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: web
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80