# Postgres for the Registry
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: registry-datastore
spec:
  serviceName: registry-datastore
  replicas: 1
  template:
    metadata:
      labels:
        service: registry-datastore
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: registry-datastore
        resources:
          requests:
            cpu: 900m
            memory: 2000Mi
        image: "data61/magda-registry-datastore:${version}"
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: /var/pv/data
        volumeMounts:
        - mountPath: /var/pv
          name: registrydata
  volumeClaimTemplates:
  - metadata:
      name: registrydata
      annotations:
        volume.beta.kubernetes.io/storage-class: fast-ssd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Gi      
---
apiVersion: v1
kind: Service
metadata:
  name: registry-datastore
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    service: registry-datastore