apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        service: gateway
    spec:
      containers:
      - name: gateway
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        env:
        - name: NODE_ENV
          value: production
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: jwt-secret
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: session-secret
        - name: FACEBOOK_CLIENT_ID
          value: "173073926555600"
        - name: FACEBOOK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: facebook-client-secret
        - name: GOOGLE_CLIENT_ID
          value: 275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: google-client-secret
        image: "data61/magda-gateway:${version}"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: gateway
  type: "LoadBalancer"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gateway
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: gateway
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80