#API
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        service: search-api
    spec:
      containers:
      - name: search-api
        env:
        - name: SCALA_ENV
          value: prod
        image: "data61/magda-search-api:${version}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: search-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: search-api
  type: "NodePort"