apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleuther-ld-rating
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        service: sleuther-ld-rating
    spec:
      containers:
      
      - name: sleuther-ld-rating
        env:
        - name: NODE_ENV
          value: prod
        - name: NODE_PORT
          value: "80"
        - name: REGISTRY_URL
          value: "http://registry-api/v0"
        image: "data61/magda-sleuther-ld-rating:${version}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sleuther-ld-rating
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: sleuther-ld-rating
  type: "NodePort"