apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: "es-data"
  replicas: 2
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "podAntiAffinity": {
              "preferredDuringSchedulingIgnoredDuringExecution": [
                {
                  "labelSelector": {
                    "matchExpressions": [
                      {
                        "key": "component",
                        "operator": "In",
                        "values": ["elasticsearch"]
                      },
                      {
                        "key": "role",
                        "operator": "In",
                        "values": ["data"]
                      }
                    ]
                  },
                  "topologyKey": "kubernetes.io/hostname",
                  "weight": 50
               },
                {
                  "labelSelector": {
                    "matchExpressions": [
                      {
                        "key": "component",
                        "operator": "In",
                        "values": ["elasticsearch"]
                      },
                      {
                        "key": "role",
                        "operator": "In",
                        "values": ["data"]
                      }
                    ]
                  },
                  "topologyKey": "kubernetes.io/hostname",
                  "weight": 50
               }
              ]
             }
           }
      #   pod.beta.kubernetes.io/init-containers: '[
      #     {
      #     "name": "sysctl",
      #       "image": "busybox",
      #       "imagePullPolicy": "IfNotPresent",
      #       "command": ["sysctl", "-w", "vm.max_map_count=262144"],
      #       "securityContext": {
      #         "privileged": true
      #       }
      #     }
      # ]'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: es-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: data61/magda-elasticsearch:${version}
        resources:
          requests:
            cpu: 800m
            memory: 8000Mi
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: NODE_MASTER
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms4000m -Xms4000m"
        - name: "ES_PLUGINS_INSTALL"
          value: "repository-gcs"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        volume.beta.kubernetes.io/storage-class: fast-ssd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Gi