# Postgres for the Registry
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: session-store
spec:
  serviceName: session-store
  replicas: 1
  template:
    metadata:
      labels:
        service: session-store
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: session-store
        resources:
          requests:
            cpu: 200m
            memory: 2000Mi
        image: "data61/magda-session-store:${version}"
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: /var/pv/data
        volumeMounts:
        - mountPath: /var/pv
          name: session-store
  volumeClaimTemplates:
  - metadata:
      name: session-store
      annotations:
        volume.beta.kubernetes.io/storage-class: fast-ssd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Gi      
---
apiVersion: v1
kind: Service
metadata:
  name: session-store
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    service: session-store
