apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-master
  labels:
    component: elasticsearch
    role: master
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      affinity:   
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - elasticsearch
                - key: role
                  operator: In
                  values:
                  - master
              topologyKey: kubernetes.io/hostname
      containers:
      - name: es-master
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: data61/magda-elasticsearch:${version}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: NUMBER_OF_MASTERS
          value: "2"
        - name: NODE_INGEST
          value: "false"
        - name: "ES_PLUGINS_INSTALL"
          value: "repository-gcs"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - emptyDir:
          medium: ""
        name: "storage"