image: {}
autoscaler:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 50m
# -- a list scssVars values that overrides the default UI scss values. <br/>
# All possible variables are defined in file: https://github.com/magda-io/magda/blob/master/magda-web-client/src/_variables.scss <br/>
# You can use this option to customise UI e.g. color. <br/>
# Example: <br/>
# <div style="border:1px solid #e7e7e7; padding-left: 5px;">
# scssVars:<br/>
# &nbsp;&nbsp;&nbsp;&nbsp;"magda-color-primary": "#395063"<br/>
# &nbsp;&nbsp;&nbsp;&nbsp;"magda-color-secondary": "#30384d"<br/>
# </div>
scssVars: {}
