global:
  useCombinedDb: true
  useCloudSql: false
  externalUrl: "http://localhost:6100"
  rollingUpdate:
    maxUnavailable: 0
  exposeNodePorts: false
  image:
    # When we don't specify tag here, .Chart.version will be used --- which is easier for versioning
    # You still can specify a tag here to override the default `.Chart.version` value (e.g. for local debugging)
    # tag: xxxxxxx
    repository: "data61"
    pullPolicy: IfNotPresent
  defaultAdminUserId: "00000000-0000-4000-8000-000000000000"
  logLevel: INFO
  noDbAuth: false
  namespace: default
  gapiIds: []
  enablePriorityClass: false
  openfaas:
    # turn on / off openfaas
    # All openfaas dependents should check this field to decide deployment logic (`tags` unfortunately not available to ).
    # They choose to simply not deploy or prompt an error message via [helm required function](https://helm.sh/docs/howto/charts_tips_and_tricks/#know-your-template-functions)
    enabled: true 
    namespacePrefix: ""
    functionNamespace: openfaas-fn  # Default namespace for functions
    mainNamespace: openfaas # Default namespace for gateway and other core modules
    allowAdminOnly: true # Only allow logged-in Admin to access openfaas gateway

openfaas:
  operator: 
    create: true
  serviceType: ClusterIP
  basic_auth: false
  ingress:
    enabled: false
  faasnetes:
    readTimeout: 120s
    writeTimeout: 120s
    imagePullPolicy: IfNotPresent
  gateway:
    scaleFromZero: true
    readTimeout: 125s
    writeTimeout: 125s
    upstreamTimeout: 120s
  faasIdler:
    dryRun: false

tags:
  # to turn on/off openfaas, please set value to `global.openfaas.enabled`
  priorities: true
  all: true
  apidocs-server: false
  admin-api: false
  authorization-api: false
  opa: false
  authorization-db: false
  combined-db: false
  content-api: false
  content-db: false
  correspondence-api: false
  elasticsearch: false
  gateway: false
  indexer: false
  preview-map: false
  registry-api: false
  registry-db: false
  search-api: false
  search-api-node: false
  session-db: false
  web-server: false
  ingress: false
  storage-api: false
  tenant-api: false
  tenant-db: false
