apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
spec:
  replicas: {{ .Values.replicas }} # default 1 in the values file
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      service: opa
  template:
    metadata:
      labels:
        service: opa
    spec:
{{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") .Values.global.enablePriorityClass }}
      priorityClassName: magda-8
{{- end }}
      containers:
      - name: opa
        image: openpolicyagent/opa:0.17.1
        imagePullPolicy: IfNotPresent
        args:
        - "run"
        - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
        - "--server"
        - "/opa-data/policies"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8181
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8181
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 10
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - name: default-opa-policies
            mountPath: /opa-raw-policy-data-files
            readOnly: true
          {{ range .Values.customPolicyConfigMaps -}}
          - name: {{.}}
            mountPath: /opa-raw-policy-data-files
            readOnly: true
          {{ end }}
      volumes:
        - name: default-opa-policies
          configMap:
            name: default-opa-policies
        {{ range .Values.customPolicyConfigMaps -}}
        - name: {{.}}
          configMap:
            name: {{.}}
        {{ end }}
