image: 
  name: "magda-authorization-api"
  # repository: 
  # tag: 
  # pullPolicy: 
  # pullSecrets: 

defaultImage:
  repository: docker.io/data61
  pullPolicy: IfNotPresent
  pullSecrets: false
  
autoscaler:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 50m

# -- when set to true, auth API will print verbose debug info (e.g. auth decision process) to log
debug: false