{{- if .Values.autoReIndex.enable -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: indexer-reindex
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.autoReIndex.schedule | quote }}
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      backoffLimit: 3
      completions: 1
      parallelism: 1
      template:
        metadata:
          name: indexer-reindex
          labels:
            cron: indexer-reindex
        spec:
          containers:
          - image: "alpine"
            imagePullPolicy: IfNotPresent
            name: indexer-reindex
            command:
              - "/bin/sh"
              - "-c"
              - "apk add --no-cache ca-certificates curl && curl -i -X POST http://indexer/v0/reindex"
          restartPolicy: OnFailure
{{- end }}
