image: 
  name: "magda-tenant-api"
  # repository: 
  # tag: 
  # pullPolicy: 
  # imagePullSecret: 

defaultImage:
  repository: docker.io/data61
  pullPolicy: IfNotPresent
  PullSecrets: false

resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 50m