apiVersion: v2
description: A Helm chart for Kubernetes
name: session-db
version: 1.0.0-alpha.0
kubeVersion: ">= 1.14.0-0"
dependencies:
- name: magda-postgresql
  version: "1.0.0-alpha.0"
  repository: "file://../magda-postgresql"
  condition: global.useInK8sDbInstance.session-db