apiVersion: v1
kind: Service
metadata:
  name: session-db
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    service: {{- if .Values.global.useCombinedDb }} "combined-db" {{- else }} "session-db" {{- end }}
