apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: es-ds
  name: es-ds
spec:
  selector:
    matchLabels:
      name: es-ds
  template:
    metadata:
      labels:
        name: es-ds
    spec:
      {{- include "magda.imagePullSecrets" (dict "image" .Values.daemonsetImage) | indent 6 }}
      containers:
      - name: es-ds
        image: {{ include "magda.image" (dict "image" .Values.daemonsetImage) | quote }}
        imagePullPolicy: {{ include "magda.imagePullPolicy" (dict "image" .Values.daemonsetImage) | quote }}
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
        securityContext:
          privileged: true
        env:
        - name: STARTUP_SCRIPT
          value: |
            #! /bin/sh
            echo "Print current vm.max_map_count value in host: "
            sysctl vm.max_map_count
            echo "Set vm.max_map_count=262144 in host:"
            sysctl -w vm.max_map_count=262144
            echo "Re-print current vm.max_map_count value in host: "
            sysctl vm.max_map_count
            echo "done!"
