{{- if .Values.autoCreateAuthSecrets }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "auth-secrets") | default dict }}
{{- /* only attempt to create secret when secret not exists or the existing secret is part of current helm release */}}
{{- if or (empty $secret) (include "magda.isPartOfRelease" $secret | empty | not) }}
{{- $secretData := (get $secret "data") | default dict }}
{{- $jwtSecret := (get $secretData "jwt-secret") | default (randAlphaNum 32 | b64enc) }}
{{- $sessionSecret := (get $secretData "session-secret") | default (randAlphaNum 32 | b64enc) }}
apiVersion: v1
kind: Secret
metadata:
  name: "auth-secrets"
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  jwt-secret: {{ $jwtSecret | quote }}
  session-secret: {{ $sessionSecret | quote }}
{{- end }}
{{- end }}