apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.postgresql.fullnameOverride }}-backup-script"
data:
  backup.sh: |
    #!/bin/sh
    export PGHOST={{ .Values.postgresql.fullnameOverride }}
    /usr/bin/envdir /etc/wal-g.d/env /usr/local/bin/wal-g backup-push
    /usr/bin/envdir /etc/wal-g.d/env /usr/local/bin/wal-g delete --confirm retain FULL {{ .Values.backupRestore.backup.archiveTimeout | default 7 }}
    