{{- if .Values.backupRestore.backup.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Values.postgresql.fullnameOverride }}-backup-jobs"
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.backupRestore.backup.schedule | quote }}
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      backoffLimit: 3
      completions: 1
      parallelism: 1
      template:
        metadata:
          name: "{{ .Values.postgresql.fullnameOverride }}-backup-job"
          labels:
            cron: "{{ .Values.postgresql.fullnameOverride }}-backup-jobs"
        spec:
{{- include "magda.pullSecrets" . | indent 10 }}
          containers:
          - image: "{{ .Values.backupRestore.image.repository }}:{{ .Values.backupRestore.image.tag }}"
            imagePullPolicy: "{{ .Values.backupRestore.image.pullPolicy }}"
            name: db-backup
            command:
              - "/bin/sh"
              - "/usr/local/bin/backup.sh"
            volumeMounts:
              - name: backup-script
                mountPath: /usr/local/bin
          restartPolicy: OnFailure
          volumes:
            - name: backup-script
              configMap:
                name: "{{ .Values.postgresql.fullnameOverride }}-backup-script"
                items:
                  - key: backup.sh
                    path: backup.sh
{{- end }}
