apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.postgresql.fullnameOverride }}-extra-env-vars"
data:
{{- if .Values.backupRestore.recoveryMode.enabled }}
  MAGDA_RECOVERY_MODE: "true"
  MAGDA_RECOVERY_BASE_BACKUP_NAME: {{ .Values.backupRestore.recoveryMode.baseBackupName | quote }}
{{- end }}
{{- with .Values.extraEnvVars }}
{{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
{{- end }}