image: {}
resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 100m
# Ckan Server URL: e.g. https://demo.ckan.org
ckanServerUrl: https://demo.ckan.org
# Ckan default API key: e.g. 1222-xxx-xxxx-xxxxx
ckanDefaultAPIKey: 9e228d18-3342-4366-9bb6-45efebbd2eb2
