{{- if .Values.global.useCombinedDb }}
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: combined-db
spec:
  serviceName: combined-db
  replicas: 1
  template:
    metadata:
      labels:
        service: combined-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: combined-db
        resources:
{{ toYaml .Values.resources | indent 10 }}
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: /var/pv/data
        {{- template "magda.postgres-env" . }}
        volumeMounts:
        - name: combined-db
          mountPath: /var/pv
        {{- template "magda.waleGoogleStorageCredentials.volumeMount" . }}
      - name: combined-db-migrator
        image: localhost:5000/data61/magda-db-migrator
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
      volumes:
      {{- template "magda.waleGoogleStorageCredentials.volume" . }}
  volumeClaimTemplates:
  - metadata:
      name: combined-db
    spec:
      accessModes: [ "ReadWriteOnce" ]
    {{- if .Values.data.storageClass }}
      storageClassName: "{{ .Values.data.storageClass }}"
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.data.storage | quote }}
{{- end }}
