{{- if .Values.global.useCombinedDb }}
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: combined-db
spec:
  serviceName: combined-db
  replicas: 1
  template:
    metadata:
      labels:
        service: combined-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: combined-db
        resources:
          requests:
            cpu: 0m
            memory: 0
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: /var/pv/data
        {{- template "magda.postgres-env" . }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/storage-account-credentials/TerriaJS-5e042b649f8a.json
        volumeMounts:
        - name: combined-db
          mountPath: /var/pv
        - name: storage-account-credentials
          mountPath: "/var/storage-account-credentials"
          readOnly: true
      volumes:
        - name: storage-account-credentials
          secret:
            secretName: storage-account-credentials
  volumeClaimTemplates:
  - metadata:
      name: combined-db
    spec:
      accessModes: [ "ReadWriteOnce" ]
    {{- if .Values.data.storageClass }}
      storageClassName: "{{ .Values.data.storageClass }}"
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.data.storage | quote }}
{{- end }}
