version: '2'
services:
  api:
    extends:
      file: docker-compose-base.yml
      service: api
    links:
      - search
    environment:
      - SCALA_ENV=dev
    build:
      context: .
      dockerfile: Dockerfile
  search:
    extends:
      file: docker-compose-base.yml
      service: search
    ports:
      - "9200:9200"
      - "9300"
  kibana:
    image: seeruk/docker-kibana-sense
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://search:9200