version: '2'
services:
  api:
    extends:
      file: docker-compose-base.yml
      service: api
#    links:
 #     - search
    environment:
      - SCALA_ENV=local
    build:
      context: .
      dockerfile: api.local.dockerfile
    ports: 
      - "8000:8000"
    volumes:
      - ../:/usr/src/app/
      - ~/.ivy2/:/root/.ivy2/
  search:
    extends:
      file: docker-compose-base.yml
      service: search
    ports:
      - "9200:9200"
      - "9300"
    volumes:
      - ../elasticsearch/scripts:/usr/share/elasticsearch/config/scripts
  kibana:
    image: seeruk/docker-kibana-sense
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://search:9200