version: '2'
services:
  api:
    extends:
      file: docker-compose-base.yml
      service: api
    environment:
      - SCALA_ENV=localdocker
    build:
      context: .
      dockerfile: api.local.dockerfile
    volumes:
      - ../:/usr/src/app/
      - ~/.ivy2/:/root/.ivy2/
    links:
      - search
    ports:
      - "9000:9000"
  search:
    extends:
      file: docker-compose-base.yml
      service: search
    build:
      context: ../elasticsearch
      dockerfile: search.local.dockerfile
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: seeruk/docker-kibana-sense
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://search:9200