apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  replicas: 1
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - name: web
        command: [
            "node", "/usr/src/app/component/dist/index.js",
            "--config", "/etc/config.json",
            "--listenPort", "80"
        ]
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: NODE_ENV
          value: production
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        volumeMounts:
        - mountPath: "/etc"
          name: config
      volumes:
      - name: config
        configMap:
          name: web-app-config
          items:
          - key: web.json
            path: config.json
