apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - name: http
    port: 80
    targetPort: 6107
{{- if .Values.global.exposeNodePorts }}
    nodePort: 30107
  type: NodePort
{{- end }}
  selector:
    service: web
