apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        service: registry-api
    spec:
      containers:
      - name: registry-api
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
        command: [
            "/app/bin/magda-registry-api",
            "-Dhttp.port=80",
            "-Dhttp.externalUrl.v0={{ .Values.global.externalUrl }}/api/v0/registry",
            "-Ddb.default.url=jdbc:postgresql://registry-datastore/postgres",
            "-Dakka.loglevel=DEBUG",
            "-DauthApi.baseUrl=http://authorization-api",
            "-Dscalikejdbc.global.loggingSQLAndTime.logLevel=info"
        ]
        ports:
        - containerPort: 80
