global:
  externalUrl: http://magda-dev.terria.io
  rollingUpdate:
    maxUnavailable: 1
  image:
    tag: "0.0.29-SNAPSHOT"
gateway:
  loadBalancerIP: "104.199.180.124"
  auth:
    facebookClientId: "173073926555600"
    googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
combined-db:
  waleBackup:
    method: WAL
    gsPrefix: "gs://magda-postgres-backups-asia/dev"