global:
  externalUrl: http://minikube.data.gov.au:30100
  rollingUpdate:
    maxUnavailable: 1
  exposeNodePorts: true
  image:
    repository: "localhost:5000/data61"
    tag: "latest"
  noDbAuth: true
  useCloudSql: false
  useCombinedDb: true

tags:
  all: false

  combined-db: true
  authorization-api: true
  authorization-db: true
  elasticsearch: true
  gateway: true
  indexer: true
  preview-map: true
  registry-api: true
  registry-db: true
  search-api: true
  session-db: true
  web-server: true
  feedback-api: true
  discussions-api: true
  discussions-db: true
  admin-api: true

gateway:
  auth:
    facebookClientId: "173073926555600"
    googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
registry-api:
  skipAuthorization: true
  # Uncomment this if you want to test postgres backups locally - download a private key from
  # google cloud, mount it as a secret and change the filename to it.
  # waleBackup:
  #   method: WAL
  #   gsPrefix: "gs://magda-postgres-backups/test"
  #   executionTime: 03:00
  #   googleApplicationCreds:
  #     secretName: storage-account-credentials
  #     fileName: <fileName>

sleuther-linked-data-rating:
  resources:
    limits:
      cpu: 0.1
sleuther-broken-link:
  resources:
    limits:
      cpu: 0.1
sleuther-visualization:
  resources:
    limits:
      cpu: 0.1
sleuther-format:
  resources:
    limits:
      cpu: 0.1