global:
  externalUrl: http://minikube.data.gov.au:30100
  rollingUpdate:
    maxUnavailable: 1
  exposeNodePorts: true
  image:
    repository: "localhost:5000/data61"
    tag: "latest"
    pullPolicy: Always
  noDbAuth: true
  useCloudSql: false
  useCombinedDb: true
  enablePriorityClass: false
  defaultContactEmail: "magda@mailinator.com"
  enableMultiTenants: false
  openfaas:
    # turn off auth over openfass gateway for ease of debugging
    allowAdminOnly: false
  urlProcessors:
    # Remove the image section to make url processors pull your test docker images from your local docker registry
    # Make sure you build & push the connector docker images to your local docker registry
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false
  connectors:
    includeInitialJobs: true
    includeCronJobs: false
    # Remove the image section to make connectors pull your test docker images from your local docker registry
    # Make sure you build & push the connector docker images to your local docker registry
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false
  minions:
    # Remove the image section to make minions pull your test docker images from local docker registry
    # Make sure you build & push the connector docker images to your local docker registry
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false

magda-core:
  gateway:
    ckanRedirectionDomain: "ckan.data.gov.au"
    ckanRedirectionPath: ""
    enableCkanRedirection: false
    enableAuthEndpoint: true
    cors:
      credentials: true
      origin: true
    auth:
      facebookClientId: "173073926555600"
      arcgisClientId: "d0MgVUbbg5Z6vmWo"
      googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
      ckanAuthenticationUrl: https://data.gov.au/data

  registry-api:
    skipAuthorization: false

  correspondence-api:
    smtpPort: 2525
    smtpHostname: "smtp.mailgun.org"

  web-server:
    fallbackUrl: "https://data.gov.au"
    showNotificationBanner: false
    featureFlags:
      cataloguing: true
      publishToDga: true
      placeholderWorkflowsOn: true
    dateConfig:
      dateFormats:
        - YYYY
        - YYYY-MM
        - DD-MM-YYYY
        - MM-DD-YYYY
        - YYYY-MM-DD
        - YYYY-MM-DDThh:mmTZD
        - YYYY-MM-DDThh:mm:ssTZD
        - YYYY-MM-DDThh:mm:ss.sTZD
        - DD-MMM-YYYY
        - MMM-DD-YYYY
      dateRegexes:
          dateRegex: "(date|dt|year|decade)"
          startDateRegex: "(start|st).*(date|dt|year|decade)"
          endDateRegex: "(end).*(date|dt|year|decade)"

  preview-map:
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false

  openfaas:
    faasnetes:
      imagePullPolicy: Always

  elasticsearch:
    data:
      resources:
        limits:
          cpu: 1000m

tags:
  all: true
  search-api-node: true
  connectors: false
  connector-dga: true

connector-dga:
  config:
    id: dga
    name: "data.gov.au"
    sourceUrl: "https://data.gov.au/"
    pageSize: 1000
    schedule: "0 * * * *"
    ignoreHarvestSources: ["*"]
