global:
  externalUrl: http://minikube.terria.io
  rollingUpdate:
    maxUnavailable: 1
  exposeNodePorts: true
  image:
    repository: "localhost:5000/data61"
    tag: "latest"
    pullPolicy: Always
  noDbAuth: true
  useCloudSql: false
  useCombinedDb: true
  enablePriorityClass: false
  defaultContactEmail: "magda@mailinator.com"
  enableMultiTenants: false
  openfaas:
    # turn on / off openfaas
    # All openfaas dependents should check this field to decide deployment logic (`tags` unfortunately not available to ).
    # They choose to simply not deploy or prompt an error message via [helm required function](https://helm.sh/docs/howto/charts_tips_and_tricks/#know-your-template-functions)
    enabled: true
    # turn off auth over openfass gateway for ease of debugging
    allowAdminOnly: false
    secrets:
      authSecrets: false
  # Remove the section to make url processors pull your test docker images from your local docker registry
  # Make sure you build & push the connector docker images to your local docker registry
  urlProcessors:
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false
  
  connectors:
    includeInitialJobs: true
    includeCronJobs: false
    # Remove the image section to make connectors pull your test docker images from your local docker registry
    # Make sure you build & push the connector docker images to your local docker registry
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false
  
  # Remove the section to make minions pull your test docker images from local docker registry
  # Make sure you build & push the connector docker images to your local docker registry
  minions: 
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false

magda:
  magda-function-history-report:
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false
  magda-core:
    gateway:
      ckanRedirectionDomain: "ckan.data.gov.au"
      ckanRedirectionPath: ""
      enableCkanRedirection: false
      enableAuthEndpoint: true
      cors:
        credentials: true
        origin: ["http://localhost:3001"]
      auth:
        googleClientId: "1039126827915-bpr6i7si9srcb9ij5hjmhljiojqufvav.apps.googleusercontent.com"
      cookie:
        # Set sameSite to "none" to explicitly allow cross-site cookie
        # It's only for allowing frontend local dev site to login to remote dev instance
        # Should not be set to "none" for a production site
        sameSite: "none"
      webRoutes:
        map: http://nsdi-digital-twin

      web: http://web
      csp: {"browserSniff":false,"directives":{"objectSrc":["''none''"],"scriptSrc":["''self''","''unsafe-inline''","browser-update.org","blob:"],"workerSrc":["''self''","blob:"]},"reportOnly":true}
      routes:
        registry:
          to: http://registry-api/v0
          auth: true
        auth:
          to: http://authorization-api/v0/public
          auth: true
        opa:
          to: http://authorization-api/v0/opa
          auth: true
          statusCheck: false   
        content:
          to: http://content-api/v0
          auth: true
        tenant:
          to: http://tenant-api/v0
          auth: true
        data:
          auth: true,
          to: http://datastore-api/v0

    registry-api:
      skipAuthorization: false

    correspondence-api:
      smtpPort: 2525
      smtpHostname: "smtp.mailgun.org"

    web-server:
      fallbackUrl: "https://data.gov.au"
      showNotificationBanner: false
      featureFlags:
        cataloguing: true
        publishToDga: true
        placeholderWorkflowsOn: true
        datasetApprovalWorkflowOn: true
      dateConfig:
        dateFormats:
          - YYYY
          - YYYY-MM
          - DD-MM-YYYY
          - MM-DD-YYYY
          - YYYY-MM-DD
          - YYYY-MM-DDThh:mmTZD
          - YYYY-MM-DDThh:mm:ssTZD
          - YYYY-MM-DDThh:mm:ss.sTZD
          - DD-MMM-YYYY
          - MMM-DD-YYYY
        dateRegexes:
            dateRegex: "(date|dt|year|decade)"
            startDateRegex: "(start|st).*(date|dt|year|decade)"
            endDateRegex: "(end).*(date|dt|year|decade)"

    preview-map:
      image:
        repository: docker.io/data61
        tag: 0.0.57-0
        pullPolicy: IfNotPresent
        imagePullSecret: false

    openfaas:
      faasnetes:
        imagePullPolicy: Always

    elasticsearch:
      data:
        resources:
          limits:
            cpu: 1000m

tags:
  all: false
  search-api-node: false
  connector-dga: false
  admin-api: false
  apidocs-server: false
  authorization-api: true
  authorization-db: true
  cloud-sql-proxy: false
  combined-db: true
  content-db: true
  content-api: true
  correspondence-api: false
  elasticsearch: false
  gateway: true
  indexer: false
  preview-map: false
  registry-api: true
  registry-db: true
  search-api: false
  session-db: true
  web-server: true
  connectors: false
  opa: true
connector-dga:
  config:
    id: dga
    name: "data.gov.au"
    sourceUrl: "https://data.gov.au/"
    pageSize: 1000
    schedule: "0 * * * *"
    ignoreHarvestSources: ["*"]
