global:
  externalUrl: http://minikube.data.gov.au:30100
  rollingUpdate:
    maxUnavailable: 1
  exposeNodePorts: true
  image:
    repository: "localhost:5000/data61"
    tag: "latest"
    pullPolicy: Always
  noDbAuth: true
  useCloudSql: false
  useCombinedDb: true
  enablePriorityClass: false
  defaultContactEmail: "magda@mailinator.com"
  enableMultiTenants: false

gateway:
  ckanRedirectionDomain: "ckan.data.gov.au"
  ckanRedirectionPath: ""
  enableCkanRedirection: true
  enableAuthEndpoint: true
  cors:
    credentials: true
    origin: true
  auth:
    facebookClientId: "173073926555600"
    arcgisClientId: "d0MgVUbbg5Z6vmWo"
    googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
    ckanAuthenticationUrl: https://data.gov.au/data

registry-api:
  skipAuthorization: false
  
correspondence-api:
  smtpPort: 2525
  smtpHostname: "smtp.mailgun.org"
  
web-server:
  fallbackUrl: "https://data.gov.au"
  featureFlags:
    cataloguing: true

connectors:
  includeCronJobs: false
  config:
    - image:
        name: "magda-ckan-connector"
      id: dga
      name: "data.gov.au"
      sourceUrl: "https://data.gov.au/"
      pageSize: 1000
      schedule: "0 * * * *"
      ignoreHarvestSources: ["*"]

content-api:
  scssVars: '{"AU-color-foreground-action":"#726a5c","AU-color-foreground-focus":"#272727","AU-color-foreground-text":"#272727","AU-color-background":"#ffffff","AU-colordark-foreground-action":"#f2f2f2","AU-colordark-foreground-focus":"#144475","AU-colordark-foreground-text":"#f2f2f2","AU-colordark-background":"#272727","header-color-background":"#726a5c","header-opacity-desktop-background":"1","header-color-border":"#726a5c","header-color-text":"#726a5c","header-color-action":"#f2f2f2","header-color-action-background":"transparent","header-color-focus":"#f2f2f2","header-color-focus-background":"#272727","header-color-mobile-toggle-button-text":"#f2f2f2","header-color-mobile-toggle-button-icon":"#f2f2f2","header-color-mobile-nav-background":"white","header-color-mobile-nav-border-bottom":"#dad9db","header-color-mobile-nav-border-left":"transparent","header-color-mobile-nav-action":"#272727","header-color-mobile-nav-action-background":"transparent","header-color-mobile-nav-active":"inherit","header-color-mobile-nav-active-background":"#f4f3f5","header-color-mobile-nav-active-border":"#272727","header-color-mobile-nav-focus":"#f4f3f5","header-color-mobile-nav-focus-background":"#272727","header-color-mobile-nav-focus-border":"transparent","header-color-mobile-nav-content":"inherit","header-color-mobile-nav-content-background":"transparent","header-color-mobile-nav-content-border-bottom":"#726a5c","footer-color-background":"#272727","footer-color-border":"#272727","footer-color-text":"#f2f2f2","footer-color-action":"#f2f2f2","footer-color-focus":"#cac8bf"}'
