global:
  useCombinedDb: false
  useCloudSql: true
  externalUrl: https://search.data.gov.au
  image:
    pullPolicy: IfNotPresent
    tag: "0.0.44-RC1"
  enableLivenessProbes: true
tags:
  all: false

  authorization-api: true
  authorization-db: true
  content-db: false
  content-api: false
  elasticsearch: true
  gateway: true
  indexer: true
  preview-map: true
  registry-api: true
  registry-db: true
  search-api: true
  session-db: true
  sleuther-broken-link: true
  sleuther-linked-data-rating: true
  sleuther-visualization: true
  sleuther-format: true
  web-server: true
  correspondence-api: true
  ingress: true


ingress:
  hostname: staging.search.data.gov.au
  ipName: staging-search-data-gov-au-ingress
  ingressClass: gce
  enableTls: true
  domains:
    - staging.search.data.gov.au
elasticsearch:
  production: true
  client:
    replicas: 2
    heapSize: 900m
    pluginsInstall: "repository-gcs"
    resources:
      requests:
        cpu: 200m
        memory: 1500Mi
  data:
    heapSize: 3000m
    pluginsInstall: "repository-gcs"
    storageClass: "fast-ssd"
    resources:
      requests:
        cpu: 800m
        memory: 5000Mi
gateway:
  ckanRedirectionDomain: "ckan.data.gov.au"
  autoscaler:
    minReplicas: 2
    maxReplicas: 4
  auth:
    facebookClientId: "173073926555600"
    googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
  csp:
    directives:
      scriptSrc:
      - "''self''"
      - "''unsafe-inline''" # For VWO, hopefully we can remove this soon
      - "data:" # Also for VWO
      - browser-update.org
      - dev.visualwebsiteoptimizer.com
      - platform.twitter.com
      - www.googletagmanager.com
      - www.google-analytics.com
      - rum-static.pingdom.net
      - https://cdnjs.cloudflare.com/ajax/libs/rollbar.js/2.4.1/rollbar.min.js
      - https://tagmanager.google.com/debug
      - assets.zendesk.com
      - static.zdassets.com
      - ekr.zdassets.com
      objectSrc:
      - "''none''"
      sandbox: # We run the sandbox because we have to have unsafe-inline, when we remove unsafe inline we should remove this
      - allow-scripts
      - allow-same-origin
      - allow-popups
      - allow-forms
      - allow-popups-to-escape-sandbox
      reportUri: https://sdga.report-uri.com/r/d/csp/enforce
  helmet:
    hsts:
      maxAge: 31536000
      includeSubdomains: true
      preload: true
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
preview-map:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
registry-api:
  logLevel: INFO
  livenessProbe:
    timeoutSeconds: 3
  resources:
    requests:
      cpu: 500m
      memory: 1000Mi
authorization-api:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
search-api:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 1000Mi
web-server:
  autoscaler:
    minReplicas: 2
    maxReplicas: 4
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  disableAuthenticationFeatures: true
  fallbackUrl: "https://data.gov.au"
sleuther-broken-link:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
sleuther-linked-data-rating:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
sleuther-visualization:
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 500Mi
sleuther-format:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
indexer:
  elasticsearch:
    shards: 2
    replicas: 4
#    useGcsSnapshots: true
#    gcsSnapshotBucket: "magda-es-snapshots"
#    gcsSnapshotServiceAccount: "_default"
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
cloud-sql-proxy:
  replicas: 2
  instanceConnectionName: terriajs:australia-southeast1:magda-prod
correspondence-api:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  defaultRecipient: "data@digital.gov.au"
  smtpHostname: "smtp.mailgun.org"
  smtpPort: 2525
