global:
  externalUrl: "https://magda.dtv.wspdigitaltesting.com"
  useCombinedDb: false
  useCloudSql: false
  useAwsRdsDb: true
  awsRdsEndpoint: dtvutilities-magda-test-db.caex0g3n4vgx.ap-southeast-2.rds.amazonaws.com

tags:
  ## "all" is a shortcut which turns on all services except minions.
  all: true
  ingress: true

connector-dga:
  config:
    id: dga
    name: "data.gov.au"
    sourceUrl: "https://data.gov.au/data/"
    pageSize: 1000
    ignoreHarvestSources: ["*"]

magda-auth-google:
  googleClientId: 770312160805-26s4qsnon6nggg499vcollhuvltujoa5.apps.googleusercontent.com

magda:
  magda-core:
    ingress:
      certificateARN: arn:aws:acm:ap-southeast-2:940728446396:certificate/e3e116c6-2f5a-42af-a196-d4030162617c

    gateway:
      service:
        type: NodePort
      authPlugins:
      - key: internal
        baseUrl: http://magda-auth-internal
      - key: google
        baseUrl: http://magda-auth-google

    web-server:
      image:
        repository: "940728446396.dkr.ecr.ap-southeast-2.amazonaws.com/magda-web-service-test"
        tag: "latest"
        pullPolicy: IfNotPresent
