#INDEXER

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: indexer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: indexer
    spec:
      containers:
      - name: indexer
        env:
        - name: SCALA_ENV
          value: prod
        - name: MAGDA_SEARCH_ROLE
          value: indexer
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-secret-key
              key: s3-secret-key
        image: "data61/magda-indexer:${version}"
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/regions
          name: regions
      volumes:
      - name: regions
        hostPath:
          path: /var/regions