apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass | default "gce" }}
  name: dev-ingress
spec:
  tls:
    - secretName: letsencrypt-staging
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.targetService | default "gateway" }}
          servicePort: 80
        path: /