apiVersion: batch/v1
kind: Job
metadata:
  name: authorization-db-migrator
  labels:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: "authorization-db-migrator"
    spec:
      restartPolicy: OnFailure
      {{- include "magda.imagePullSecrets" . | indent 6 }}
      containers:
      - name: authorization-db-migrator
        image: {{ include "magda.image" . | quote }}
        imagePullPolicy: {{ include "magda.imagePullPolicy" . | quote }}
        env:
        - name: DB_HOST
          value: authorization-db
        {{- include "magda.postgres-migrator-env" . | indent 8 }}
