image: {}
  #repository: data61/
  #tag: latest
  #pullPolicy: Always#
autoscaler:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 100m
disableAuthenticationFeatures: false
service: {}
useLocalStyleSheet: false
contentApiBaseUrlInternal: "http://content-api/v0/"
featureFlags:
 cataloguing: false
 previewAddDataset: false
vocabularyApiEndpoints: []
defaultContactEmail: "mail@example.com"
custodianOrgLevel: 2
# default max preview file size 2mib
automaticPreviewMaxFileSize: 2097152
mandatoryFields:
  - dataset.title
  - dataset.description
  - dataset.defaultLicense
  - files.title
  - files.format
  - files.license
  - dataset.publisher
  - licenseLevel
  - dataset.defaultLicense
  - files.license
  - informationSecurity.classification
  - informationSecurity.disseminationLimits