image: 
  name: "magda-apidocs-server"
  # repository: 
  # tag: 
  # pullPolicy: 
  # imagePullSecret: 

defaultImage:
  repository: docker.io/data61
  pullPolicy: IfNotPresent
  imagePullSecret: false

resources:
  requests:
    cpu: 10m
    memory: 10Mi
  limits:
    cpu: 20m
