image: {}
loaderImage: 
  # Github repo: https://github.com/magda-io/magda-configmap-dir-loader
  repository: docker.io/data61
    tag: 0.0.57-0
    pullPolicy: IfNotPresent
    imagePullSecret: false
autoscaler:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
replicas: 1
resources:
  requests:
    cpu: 20m
    memory: 50Mi
  limits:
    cpu: 100m
customPolicyConfigMaps: []