apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: admin-api
    spec:
      containers:
      - name: admin-api
        resources:
          requests:
            memory: 0
        env:
        - name: NODE_ENV
          value: minikube
        - name: JWT_SECRET
          value: squirrel
        image: "localhost:5000/data61/magda-admin-api:latest"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: admin-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30018
  selector:
    service: admin-api
  type: "NodePort"