apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discussions-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: discussions-api
    spec:
      containers:
      - name: discussions-api
        resources:
          requests:
            memory: 0
        env:
        - name: NODE_ENV
          value: minikube
        - name: JWT_SECRET
          value: squirrel
        image: "localhost:5000/data61/magda-discussions-api:latest"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: discussions-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30017
  selector:
    service: discussions-api
  type: "NodePort"