# Indexer
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: indexer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: indexer
    spec:
      containers:
      - name: indexer
        resources:
          requests:
            memory: 0
        env:
        - name: SCALA_ENV
          value: local
        image: "localhost:5000/data61/magda-indexer:latest"
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/regions
          name: regions
      volumes:
      - name: regions
        hostPath:
          path: /tmp/regions
---
apiVersion: v1
kind: Service
metadata:
  name: indexer
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30012
  - name: debug
    port: 8000
    targetPort: 8000
    nodePort: 30081
  selector:
    service: indexer
  type: "NodePort"
