# Registry API
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: registry-api
    spec:
      containers:
      - name: registry-api
        env:
        - name: SCALA_ENV
          value: local
        resources:
          requests:
            cpu: 0m
        image: "localhost:5000/data61/magda-registry-api:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: registry-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30010
  selector:
    service: registry-api
  type: "NodePort"