# Search API
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: search-api
    spec:
      containers:
      - name: search-api
        resources:
          requests:
            memory: 0
        env:
        - name: SCALA_ENV
          value: local
        image: "localhost:5000/data61/magda-search-api:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 8000
        volumeMounts:
        - mountPath: /usr/regions
          name: regions
      volumes:
      - name: regions
        hostPath:
          path: /tmp/regions
---
apiVersion: v1
kind: Service
metadata:
  name: search-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30009
  - name: debug
    port: 8000
    targetPort: 8000
    nodePort: 30080
  selector:
    service: search-api
  type: "NodePort"