apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - name: web
        resources:
          requests:
            memory: 0
        env:
        - name: NODE_ENV
          value: minikube
        image: "localhost:5000/data61/magda-web:latest"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30017
  selector:
    service: web
  type: "NodePort"
