apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8-dtv-terriamap
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: wsp-digital/dtvutilities-terriamap