apiVersion: v1
kind: ConfigMap
metadata:
  name: "opa-policies"
  labels:
    pod: "opa"
data:
{{- range $path, $bytes := .Files.Glob "policies/**/*" }}
{{- $str := toString $bytes }}
{{- $lines := splitList "\n" $str }}
  {{ base $path }}: |-
  {{- range $lines }}
  {{ . | indent 2 }}
  {{- end }}
{{- end }}
