apiVersion: v1
kind: Service
metadata:
  name: registry-datastore
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    service: {{- if .Values.global.useCombinedDb }} "combined-db" {{- else }} "registry-datastore" {{- end }}
