# Postgres for the Registry
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: registry-datastore
spec:
  serviceName: registry-datastore
  replicas: 1
{{- if semverCompare "^1.7.0" (printf "%s" .Capabilities.KubeVersion) }}
  updateStrategy:
    type: RollingUpdate
{{- end }}
  template:
    metadata:
      labels:
        service: registry-datastore
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: registry-datastore
        resources:
{{ toYaml .Values.resources | indent 10 }}
        image: {{ template "dockerimage" . }}
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: /var/pv/data
        volumeMounts:
        - mountPath: /var/pv
          name: registrydata
  volumeClaimTemplates:
  - metadata:
      name: registrydata
      annotations:
        volume.beta.kubernetes.io/storage-class: fast-ssd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Gi
