# -- migrator docker image settings
image: 
  name: "magda-migrator-content-db"
  # repository: 
  # tag: 
  # pullPolicy: 
  # imagePullSecret: 

defaultImage:
  repository: docker.io/data61
  pullPolicy: IfNotPresent
  imagePullSecret: false

# -- whether auto-create secret for client account password.
# After the migrator runs properly, a non-superuser DB account (named `client`) will be created.
# Its password will loaded from secret `{{ .Chart.Name }}-password` (e.g. `authorization-db-passwor`) & key: `password`.
# Set this option to `true` will make helm auto-create the secret with random password, ONLY when the secret not exists.
autoCreateSecret: true

magda-postgres:
  postgresql: 
    fullnameOverride: "content-db-postgresql"
    nameOverride: "content-db-postgresql"
    persistence:
      size: "50Gi"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi