apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: api
spec:
  ports:
  - name: "main"
    port: 80
    protocol: "TCP"
    targetPort: 9000
    nodePort: 39000
  - name: "debug"
    port: 8000
    protocol: "TCP"
    targetPort: 8000
    nodePort: 30001
  selector:
    service: api
  type: "LoadBalancer"
status:
  loadBalancer: {}
