apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: kibana
spec:
  ports:
  - name: "kibana"
    port: 5601
    protocol: "TCP"
    targetPort: 5601
  selector:
    service: kibana
status:
  loadBalancer: {}
