apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    service: kibana
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://search:9200
        image: seeruk/docker-kibana-sense
        imagePullPolicy: ""
        name: kibana
        ports:
        - containerPort: 5601
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
