#API

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    service: api
  template:
    metadata:
      labels:
        service: api
    spec:
      containers:
      - name: api
        env:
        - name: SCALA_ENV
          value: local
        image: "alexgilleran/magda-metadata:v0.0.1"
        ports:
        - containerPort: 9000
        - containerPort: 8000
        volumeMounts:
        - mountPath: /usr/regions
          name: regions
        - mountPath: /usr/src/app/
          name: src
        - mountPath: /root/.ivy2/
          name: ivy-cache
      volumes:
      - name: regions
        hostPath:
          path: ${projectDir}/regions
      - hostPath:
          path: ${projectDir}
        name: src
      - hostPath:
          path: ${homeDir}/.ivy2/
        name: ivy-cache
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 80
    targetPort: 9000
    nodePort: 30009
  - port: 8000
    targetPort: 8000
    nodePort: 30008
  selector:
    service: api
  type: "LoadBalancer"
---

# ELASTIC SEARCH
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search
spec:
  replicas: 1
  selector:
    service: search
  template:
    metadata:
      labels:
        service: search
    spec:
      containers:
      - name: search
        env:
        - name: ES_HEAP_SIZE
          value: 2g
        image: elasticsearch:2.4
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: data
          hostPath:
            path: ${projectDir}/.esdata
    
---
apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30092
  - port: 9300
    targetPort: 9300
    nodePort: 30093
  selector:
    service: search
---
    
# KIBANA
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    service: kibana
  template:
    metadata:
      labels:
        service: kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://search:30092
        image: seeruk/docker-kibana-sense
        name: kibana
        ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30056
  selector:
    service: kibana

