apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: search
spec:
  ports:
  - name: "java"
    port: 9200
    protocol: "TCP"
    targetPort: 9300
  - name: "http"
    port: 9300
    protocol: "TCP"
    targetPort: 9300
  selector:
    service: search
status:
  loadBalancer: {}
