apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: {{ .Values.replicas | default 1 }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      service: search-api
  template:
    metadata:
      labels:
        service: search-api
    spec:
{{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1") .Values.global.enablePriorityClass }}
      priorityClassName: magda-8
{{- end }}
      {{- include "magda.imagePullSecrets" . | indent 6 }}
      containers:
      - name: search-api
        image: {{ include "magda.image" . | quote }}
        imagePullPolicy: {{ include "magda.imagePullPolicy" . | quote }}
        command:
          - "/app/bin/magda-search-api"
          - "-Dhttp.port=80"
          - "-Dakka.loglevel={{ .Values.global.logLevel }}"
          - "-Dopa.baseUrl=http://authorization-api/v0/opa/"
          - "-DelasticSearch.serverUrl=elasticsearch://elasticsearch:9200"
{{- if .Values.datasetsIndexVersion }}
          - "-DelasticSearch.indices.datasets.version={{ .Values.datasetsIndexVersion }}"
{{- end }}
{{- if .Values.regionsIndexVersion }}
          - "-DelasticSearch.indices.regions.version={{ .Values.regionsIndexVersion }}"
{{- end }}
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: /v0/status/live
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /v0/status/ready
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
{{- end }}
        ports:
        - containerPort: 80
        resources:
{{ toYaml .Values.resources | indent 10 }}
