{{- if .Values.defaultCertificate }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: magda-cert
spec:
  secretName: magda-cert-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: {{ index .Values.defaultCertificate.domains 0 | quote }}
  dnsNames:
  {{- range .Values.defaultCertificate.domains }}
  - {{ . | quote }}
  {{- end }}
{{- end }}
