apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: auth-api
    spec:
      containers:
      - name: auth-api
        resources:
          requests:
            memory: 0
        env:
        - name: NODE_ENV
          value: development
        image: "localhost:5000/data61/magda-auth-api:latest"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30015
  selector:
    service: auth-api
  type: "NodePort"