apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: auth-gateway
    spec:
      containers:
      - name: auth-gateway
        resources:
          requests:
            memory: 0
        env:
        - name: NODE_ENV
          value: minikube
        - name: JWT_SECRET
          value: squirrel
        - name: SESSION_SECRET
          value: "keyboard cat"
        - name: FACEBOOK_CLIENT_ID
          value: "173073926555600"
        - name: FACEBOOK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: facebook-client-secret
        - name: GOOGLE_CLIENT_ID
          value: 275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: google-client-secret
        image: "localhost:5000/data61/magda-auth-gateway:latest"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-gateway
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30016
  selector:
    service: auth-gateway
  type: "NodePort"