apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: ckan-connector
spec:
  schedule: "* * */3 * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: ckan-connector
        spec:
          containers:
          - name: ckan-connector
            image: localhost:5000/data61/magda-ckan-connector:latest
            env:
            - name: "REGISTRY_URL"
              value: "http://registry-api"
          restartPolicy: Never