# Search API
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: search-api
    spec:
      containers:
      - name: search-api
        resources:
          requests:
            memory: 0
        env:
        - name: SCALA_ENV
          value: local
        image: "localhost:5000/data61/magda-search-api:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 8000
        volumeMounts:
        - mountPath: /usr/regions
          name: regions
      volumes:
      - name: regions
        hostPath:
          path: /tmp/regions
---
apiVersion: v1
kind: Service
metadata:
  name: search-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30009
  - name: debug
    port: 8000
    targetPort: 8000
    nodePort: 30080
  selector:
    service: search-api
  type: "NodePort"
---
# Registry API
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: registry-api
    spec:
      containers:
      - name: registry-api
        resources:
          requests:
            memory: 0
        env:
        - name: SCALA_ENV
          value: local
        image: "localhost:5000/data61/magda-registry-api:latest"
---
apiVersion: v1
kind: Service
metadata:
  name: registry-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30010
  - name: debug
    port: 8000
    targetPort: 8000
    nodePort: 30100
  selector:
    service: registry-api
  type: "NodePort"
---
# CKAN Connector
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ckan-connector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: ckan-connector
    spec:
      containers:
      - name: ckan-connector
        resources:
          requests:
            memory: 0
        env:
        - name: SCALA_ENV
          value: local
        image: "localhost:5000/data61/magda-ckan-connector:latest"
---
apiVersion: v1
kind: Service
metadata:
  name: ckan-connector
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30011
  - name: debug
    port: 8000
    targetPort: 8000
    nodePort: 30110
  selector:
    service: ckan-connector
  type: "NodePort"
---
# Indexer
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: indexer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: indexer
    spec:
      containers:
      - name: indexer
        resources:
          requests:
            memory: 0
        env:
        - name: SCALA_ENV
          value: local
        image: "localhost:5000/data61/magda-metadata-indexer:latest"
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/regions
          name: regions
      volumes:
      - name: regions
        hostPath:
          path: /tmp/regions
---
apiVersion: v1
kind: Service
metadata:
  name: indexer
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30012
  - name: debug
    port: 8000
    targetPort: 8000
    nodePort: 30081
  selector:
    service: indexer
  type: "NodePort"
