# Indexer
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        resources:
          requests:
            memory: 0
        image: "localhost:5000/data61/magda-reverse-proxy:latest"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30013
  selector:
    service: reverse-proxy
  type: "NodePort"