image: {}
  #repository: data61/
  #tag: latest
  # pullPolicy: Always
gitHubIssuesUrl:
resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 50m
smtpPort: 587
defaultRecipient: "mail@example.com"