image: {}
resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 50m

minio:
  host: "minio"
  port: 9000
  nameOverride: "magda-minio"
  fullnameOverride: "magda-minio"
  existingSecret: "storage-secrets"
  resources:
    requests:
      memory: 256Mi
  DeploymentUpdate:
    type: Recreate

