#INDEXER
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: indexer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: indexer
    spec:
      containers:
      
      - name: indexer
        env:
        - name: SCALA_ENV
          value: dev
        image: "data61/magda-indexer:${version}"
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/regions
          name: regions
      volumes:
      - name: regions
        hostPath:
          path: /var/regions
---
apiVersion: v1
kind: Service
metadata:
  name: indexer
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: indexer
  type: "NodePort"