apiVersion: batch/v1
kind: Job
metadata:
  name: registry-aspect-definition-migrator
  labels:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: {{ .Values.aspectDefinitionMigrator.backoffLimit | default 6 }}
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: "registry-aspect-definition-migrator"
    spec:
      restartPolicy: OnFailure
      {{- include "magda.imagePullSecrets" (dict "image" .Values.aspectDefinitionMigrator.image) | indent 6 }}
      containers:
      - name: registry-aspect-definition-migrator
        image: {{ include "magda.image" (dict "image" .Values.aspectDefinitionMigrator.image) | quote }}
        imagePullPolicy: {{ include "magda.imagePullPolicy" (dict "image" .Values.aspectDefinitionMigrator.image) | quote }}
        command: 
          - "node"
          - "/usr/src/app/component/dist/index.js"
          - "--registryUrl"
          - "http://registry-api/v0"
        env: 
        - name: USER_ID
          value: {{ .Values.global.defaultAdminUserId }}
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
