magda-postgres:
  postgresql: 
    fullnameOverride: "combined-db-postgresql"
    nameOverride: "combined-db-postgresql"
    persistence:
      size: "100Gi"
    resources:
      requests:
        cpu: 200m
        memory: 500Mi


