# Indexer
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        resources:
          requests:
            memory: 0
        image: "data61/magda-reverse-proxy:${version}"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: reverse-proxy
  type: "LoadBalancer"
  loadBalancerIP: "104.199.180.124"