apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleuther-broken-link
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: sleuther-broken-link
    spec:
      containers:
      
      - name: sleuther-broken-link
        env:
        - name: NODE_ENV
          value: dev-na
        - name: NODE_PORT
          value: "80"
        - name: REGISTRY_URL
          value: "http://registry-api/v0"
        image: "data61/magda-sleuther-broken-link:${version}"
        resources:
          requests:
            cpu: 0m
            memory: 0Mi
          limits:
            cpu: 500m
            memory: 200Mi
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sleuther-broken-link
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: sleuther-broken-link
  type: "NodePort"