apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: preview-map
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: preview-map
    spec:
      containers:
      - name: preview-map
        resources:
          requests:
            cpu: 0m
            memory: 0
        env:
        - name: NODE_ENV
          value: dev-na
        image: "data61/magda-preview-map:${version}"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: preview-map
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3019
  selector:
    service: preview-map
  type: "NodePort"
