apiVersion: batch/v1
kind: Job
metadata:
  name: ckan-connector
spec:
  template:
    metadata:
      name: ckan-connector
    spec:
      containers:
      - name: ckan-connector
        image: data61/magda-ckan-connector:${version}
        resources:
          requests:
            cpu: 0m
        env:
        - name: "REGISTRY_URL"
          value: "http://registry-api/v0"
      restartPolicy: OnFailure