# Postgres for EVERYTHING
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: combined-db
spec:
  serviceName: combined-db
  replicas: 1
  template:
    metadata:
      labels:
        service: combined-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: combined-db
        resources:
          requests:
            cpu: 0m
            memory: 0
        image: data61/magda-combined-db:${version}
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: /var/pv/data
        volumeMounts:
        - mountPath: /var/pv
          name: combined-db
  volumeClaimTemplates:
  - metadata:
      name: combined-db
      annotations:
        volume.beta.kubernetes.io/storage-class: spinning-rust
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Gi    
---
apiVersion: v1
kind: Service
metadata:
  name: combined-db
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    service: combined-db
  type: "NodePort"
