{
  "apiVersion": "batch/v1",
  "kind": "Job",
  "metadata": {
    "name": "broken-link-sleuther"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "broken-link-sleuther"
      },
      "spec": {
        "containers": [
          {
            "name": "broken-link-sleuther",
            "image": "data61/magda-broken-link-sleuther:${version}",
            "imagePullPolicy": "Always",
            "resources": {
              "requests": {
                "cpu": "100m"
              }
            },
            "env": [
                {
                    "name": "REGISTRY_URL",
                    "value": "http://registry-api/v0"
                }
            ]
          }
        ],
        "restartPolicy": "OnFailure"
      }
    }
  }
}
