apiVersion: batch/v1
kind: Job
metadata:
  name: data-gov-au-connector
spec:
  template:
    metadata:
      name: data-gov-au-connector
    spec:
      containers:
      - name: ckan-connector
        image: data61/magda-ckan-connector:${version}
        args: [
            "node", "/usr/src/app/@magda/ckan-connector/bin/index.js",
            "--config", "/etc/config/connector.json",
            "--registryUrl", "http://registry-api/v0"
        ]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0m
        volumeMounts:
        - mountPath: /etc/config
          name: config
      restartPolicy: OnFailure
      volumes:
        - name: config
          configMap:
            name: connector-config
            items:
            - key: data-gov-au.json
              path: connector.json
