apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: gateway
    spec:
      containers:
      - name: gateway
        resources:
          requests:
            cpu: 0m
            memory: 0
        env:
        - name: NODE_ENV
          value: dev-na
        - name: NODE_PORT
          value: "80"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: jwt-secret
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: session-secret
        - name: FACEBOOK_ENABLED
          value: "true"
        - name: FACEBOOK_CLIENT_ID
          value: "173073926555600"
        - name: FACEBOOK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: facebook-client-secret
        - name: GOOGLE_ENABLED
          value: "true"
        - name: GOOGLE_CLIENT_ID
          value: 275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secrets
              key: google-client-secret
        - name: CKAN_ENABLED
          value: "true"
        image: "data61/magda-gateway:${version}"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: gateway
  type: "LoadBalancer"
  loadBalancerIP: "104.199.180.124"