#VARNISH
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: varnish
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: varnish
    spec:
      containers:
      - name: varnish
        image: "mobulum/varnish"
        resources:
          requests:
            cpu: 0m
        imagePullPolicy: Always
        env:
        - name: BACKEND_PORT_80_TCP_ADDR
          value: search-api
        - name: BACKEND_ENV_PORT
          value: "80"
        - name: LISTEN_PORT
          value: "80"
        - name: THROTTLE_LIMIT
          value: "150req/30s"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: varnish
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: varnish
  type: "LoadBalancer"
#  loadBalancerIP: "104.199.177.83"
---
#API
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: search-api
    spec:
      containers:
      - name: search-api
        env:
        - name: SCALA_ENV
          value: dev-na
        image: "data61/magda-search-api:${version}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: search-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: search-api
  type: "NodePort"