apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - name: web
        command: [
            'node', '/usr/src/app/component/bin/index.js',
            '--config', "/etc/config.json"
        ]
        resources:
          requests:
            cpu: 0m
            memory: 0
        env:
        - name: NODE_ENV
          value: dev-na
        image: "data61/magda-web-server:${version}"
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/etc"
          name: config
      volumes:
      - name: config
        configMap:
          name: config
          items:
          - key: web.json
            path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: web
  type: "NodePort"
