apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - name: web
        resources:
          requests:
            cpu: 0m
            memory: 0
        env:
        - name: NODE_ENV
          value: dev-na
        image: "data61/magda-web-server:${version}"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: web
  type: "NodePort"
