apiVersion: v1
kind: ConfigMap
metadata:
  name: "gateway-config"
  labels:
    pod: "gateway"
data:
  # When the config map is mounted as a volume, these will be created as files.
  webRoutes.json: {{ .Values.routes | default .Values.defaultRoute | mustToRawJson | quote }}
  webRoutes.json: {{ .Values.webRoutes | default {} | mustToRawJson | quote }}
  helmet.json: {{ .Values.helmet | default {} | mustToRawJson | quote }}
  cors.json: {{ .Values.cors | default {} | mustToRawJson | quote }}
  csp.json: {{ .Values.csp | default {} | mustToRawJson | quote }}
  cookie.json: {{ .Values.cookie | default {} | mustToRawJson | quote }}
  authPlugins.json: {{ .Values.global.authPlugins | default [] | mustToRawJson | quote }}

