apiVersion: v1
kind: Service
metadata:
  name: sleuther-broken-link
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
{{- if .Values.global.exposeNodePorts }}
    nodePort: 30111
  type: NodePort
{{- end }}
  selector:
    service: sleuther-broken-link
