apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: {{- if .Values.useStaging }} "https://acme-staging-v02.api.letsencrypt.org/directory" {{- else }} https://acme-v02.api.letsencrypt.org/directory {{- end }}
    email: {{ .Values.acmeEmail }}

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt

    # ACME DNS-01 provider configurations
    dns01:
      providers:
        - name: prod-dns
          route53:
            region: ap-southeast-2
            hostedZoneID: Z1FY04JPVA0ZUP
            accessKeyID: AKIAJLPF6GKZMIUFYOXQ 
            secretAccessKeySecretRef:
              name: prod-route53-credentials-secret
              key: secret-access-key