apiVersion: batch/v1
kind: Job
metadata:
  name: ckan-connector
spec:
  template:
    metadata:
      name: ckan-connector
    spec:
      containers:
      - name: ckan-connector
        image: localhost:5000/data61/magda-ckan-connector:latest
        # command: ["node",  "/usr/src/app/bin/index.js"]
      restartPolicy: Never