{{- if and .Values.global.exposeNodePorts .Values.global.useCloudSql }}
apiVersion: v1
kind: Service
metadata:
  name: cloud-sql-proxy
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
{{- if .Values.global.exposeNodePorts }}
    nodePort: 30543
  type: NodePort
{{- end }}
  selector:
    service: cloud-sql-proxy
{{- end }}