apiVersion: v1
kind: ConfigMap
metadata:
  name: "web-app-config"
data:
  {{- $webConfigDict := omit .Values "global" "image" "autoscaler" "resources" "service" }}
  {{- $_ := set $webConfigDict "baseExternalUrl" .Values.global.externalUrl }}
  {{- $_ := set $webConfigDict "authPluginRedirectUrl" .Values.global.authPluginRedirectUrl }}
  {{- $_ := .Values.global.useLocalStyleSheet | default .Values.useLocalStyleSheet | set $webConfigDict "useLocalStyleSheet" }}
  web.json: {{ $webConfigDict | mustToRawJson | quote }}
