apiVersion: v1
kind: ConfigMap
metadata:
  name: "web-app-config"
data:
  {{- $webConfigDict := omit .Values "global" "autoscaler" "resources" "service" "replicas" }}
  {{- $_ := set $webConfigDict "baseExternalUrl" .Values.global.externalUrl }}
  {{- $_ := set $webConfigDict "authPluginRedirectUrl" .Values.global.authPluginRedirectUrl }}
  {{- $_ := .Values.global.useLocalStyleSheet | default .Values.useLocalStyleSheet | set $webConfigDict "useLocalStyleSheet" }}
  {{- $_ := .Chart.Version | dict "tag" | merge (.Values.global.image | default dict | deepCopy | merge (deepCopy .Values.image)) | set $webConfigDict "image" }}
  web.json: {{ $webConfigDict | mustToRawJson | quote }}
