dependencies:
  - name: magda-core
    version: 0.0.57-0
    repository: file://../magda-core
  # magda-core chart is always enabled.
  # Thus, no tags or condition are required.
  # You should set its sub-chart to enabled or not.

  - name: openfaas
    version: 5.5.4
    repository: https://openfaas.github.io/faas-netes/
    condition: global.deployOpenfaas
  
  - name: magda-minion-broken-link
    alias: minion-broken-link
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - minion-broken-link

  - name: magda-minion-format
    alias: minion-format
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - minion-format

  - name: magda-minion-linked-data-rating
    alias: minion-linked-data-rating
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - minion-linked-data-rating

  - name: magda-minion-visualization
    alias: minion-visualization
    version: 0.0.57-0
    repository: https://charts.magda.io
    tags:
      - minion-visualization

  - name: magda-ckan-connector
    version: 0.0.57-0-openfaas
    alias: connector-dga
    repository: https://charts.magda.io
    tags:
      - connectors
      - connector-dga
