global:
  useCombinedDb: true
  externalUrl: "http://localhost:6100"
  rollingUpdate:
    maxUnavailable: 0
  exposeNodePorts: false
  image:
    repository: "data61"
    tag: "0.0.29"
    pullPolicy: Always
  defaultAdminUserId: "00000000-0000-4000-8000-000000000000"
  logLevel: INFO
  noDbAuth: false
tags:
  all: true
  authorization-api: false
  authorization-db: false
  combined-db: false
  elasticsearch: false
  gateway: false
  indexer: false
  preview-map: false
  registry-api: false
  registry-datastore: false
  search-api: false
  session-store: false
  web-server: false
  sleuther-broken-link: false
  sleuther-linked-data-rating: false