tags:
  all: true
  connectors: false
  minion-broken-link: false
  minion-linked-data-rating: false
  minion-visualization: false
  minion-format: false

global:
  connectors:
    includeInitialJobs: false
    includeCronJobs: true
  openfaas:
    namespacePrefix: ""
    functionNamespace: openfaas-fn  # Default namespace for functions
    mainNamespace: openfaas # Default namespace for gateway and other core modules
    allowAdminOnly: true # Only allow logged-in Admin to access openfaas gateway

ckan-connector-functions:
  includeInitialJobs: false
  includeCronJobs: false
  createFunction: true
  createConfigMap: false