# -- migrator docker image settings
image: {}
  #repository: data61/
  #tag: latest
  # pullPolicy: Always

# -- whether auto-create secret for client account password.
# After the migrator runs properly, a non-superuser DB account (named `client`) will be created.
# Its password will loaded from secret `{{ .Chart.Name }}-password` (e.g. `authorization-db-passwor`) & key: `password`.
# Set this option to `true` will make helm auto-create the secret with random password, ONLY when the secret not exists.
autoCreateSecret: true

postgresql-wrapper:
  postgresql: 
    fullnameOverride: "registry-db-postgresql"
    nameOverride: "registry-db-postgresql"
    persistence:
      size: "100Gi"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
autoVacuum:
  enable: true
  # -- auto vacuum cronjob schedule string. specified using unix-cron format (in UTC timezone by default).
  # @default -- "0 19 * * *": 7:00PM UTC timezone (5:00AM in AEST Sydney timezone) daily
  schedule: "0 19 * * *" 