name: Deploy magda-web-server

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch or ref to deploy"
        required: true
        default: "next"

env:
  AWS_DEFAULT_REGION: ap-southeast-2

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "next"

      - name: 'Upgrade Deps'
        uses: WyriHaximus/github-action-helm3@v2.0
        with:
          exec: helm dep up deploy/helm/wsp-magda

      - name: 'Deploy'
        uses: WyriHaximus/github-action-helm3@v2.0
        with:
          exec: helm upgrade --namespace magda --install --timeout 9999s magda deploy/helm/wsp-magda -f deploy/helm/wsp-deploy-test.yml --set "magda.magda-core.web-server.image.tag=${GITHUB_SHA::8}"
          kubeconfig: '${{ secrets.KUBECONFIG }}'
