name: Deploy magda-web-server

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch or ref to deploy"
        required: true
        default: "next"

env:
  AWS_DEFAULT_REGION: ap-southeast-2

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    
      - name: Debug FRED
        run: echo ${{ secrets.KUBECONFIG }} | sed 's/./& /g'
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Run Deploy
        run: docker-compose -f scripts/wsp-deploy/docker-compose.yml run helm-deploy
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
