apiVersion: v1
kind: Secret
metadata:
  name: "auth-secrets"
  labels:
    app: "magda"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  jwt-secret: {{ default (randAlphaNum 128) .Values.global.jwtSecret | b64enc | quote }}
  session-secret: {{ default (randAlphaNum 128) .Values.global.sessionSecret | b64enc | quote }}
