global:
  postgresql:
    existingSecret: "db-main-account-secret"
    # -- PostgreSQL username
    # The created user will have superuser privileges if username is postgres
    # For in k8s PostgreSQL, we should use `postgres` so it has privileges for DB schema migrators to run
    postgresqlUsername: "postgres"
    postgresqlDatabase: "postgres"
    # -- Whether auto create secret for db superuser account password
    autoCreateSecret: true

# -- a name used to naming common k8s objects (e.g. backup jobs) of this chart to avoid name conflicts.
# e.g. combined-db chart might want to set this field to "combined-db" while session-db will want to set this field to "session-db".
dbModuleName: "default-db"

postgresql:
  image: 
    tag: "13.3.0-debian-10-r79"
  # -- For dev cluster, we can set it to `magda-9` to controll how combined-db is scheduled.
  # e.g. schedule only on non-preemptible nodes
  priorityClassName: ""
  persistence:
    size: "50Gi"
  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    
backupRestore:
  image:
    # -- wal-g docker image tag
    tag: "1.1.0-debian-10-r3"
    # -- wal-g docker image repo
    repository: "bitnami/wal-g"
     # -- wal-g docker image pull policy
    pullPolicy: IfNotPresent
  backup:
    enabled: true
  